#! /bin/sh


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          28

/home/patrik/.local/bin/polybar.sh
xautolock -detectsleep -time 20 -locker "/usr/bin/sudo /usr/bin/zzz" &


bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^3'
bspc rule -a mocp desktop='^4'
bspc rule -a mplayer state=floating
#bspc rule -a mpv desktop='^6' follow=on
bspc rule -a Tor Browser state=floating
